name: trip-pip-backend

services:
  backend:
    image: ${DOCKER_USERNAME}/trip-pip-backend:${TAG}
    restart: unless-stopped
    environment:
      HTTP_ADDR: ":8080"
    ports:
      - "8077:8080"
    read_only: true
    security_opt:
      - no-new-privileges:true

    networks:
      - trip-pip-network

networks:
  trip-pip-network:
    external: true